### ISSUE TITLE
NullReferenceException when using InteractivityExtension.WaitForEventArgsAsync<T>(Func<T, bool> predicate)

### ISSUE THREAD

**Issue by MichaelPrust** [DSharpPlus/DSharpPlus#1133]
Hello, these errors are occurring every time a user interacts with components "catched" by a InteractivityExtension.WaitForEventArgsAsync<T>(Func<T, bool> predicate):

```
[2021-10-17 02:02:12 -03:00] [104 /EventHandler] [Error] Event handler exception for event COMPONENT_INTERACTED thrown from System.Threading.Tasks.Task HandleEvent(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.ComponentInteractionCreateEventArgs) (defined in DSharpPlus.Interactivity.EventHandling.EventWaiter`1[DSharpPlus.EventArgs.ComponentInteractionCreateEventArgs])
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Interactivity.EventHandling.EventWaiter`1.HandleEvent(DiscordClient client, T eventargs)
   at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)
[2021-10-17 02:02:12 -03:00] [42  /HossamBot   ] [Error] Exception occured
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Interactivity.EventHandling.EventWaiter`1.HandleEvent(DiscordClient client, T eventargs)
   at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)
```

I'm using the `ComponentInteractionCreateEventArgs` for the parameters `T` and `p => p?.Message?.Id == msgId` for the `predicate`.

The args is returned fine, but the log screen has a lot of these errors.

v4.1.0

**Comment by VelvetThePanda** [comment]
Is this reproducible on nightlies? There have been several bug-fixes regarding both components & interactivity since the 4.1.0 release.

**Comment by MichaelPrust** [comment]
> 
> 
> Is this reproducible on nightlies? There have been several bug-fixes regarding both components & interactivity since the 4.1.0 release.

its keep happening with a fresh build from the main branch

**Comment by Emzi0767** [comment]
Try nightlies, notb self-builds

**Comment by kuylar** [comment]
Just tried to reproduce this using the following code with no success (no errors on my side), does it still happen in the latest nightly version?

```cs
var res = await interactivity.WaitForEventArgsAsync<ComponentInteractionCreateEventArgs>(x => x.Message.Id == mesg.Id);

Console.WriteLine(res.Result.Message.Content + " -> " + res.Result.Id);
```

![image](https://user-images.githubusercontent.com/52961639/162586026-337ff0c2-1e7e-42dd-88dd-889d96c869ec.png)
![image](https://user-images.githubusercontent.com/52961639/162585937-a202d181-7af2-4d82-965a-f916c1a9fbb9.png)

**Comment by DWaffles** [comment]
> Just tried to reproduce this using the following code with no success (no errors on my side), does it still happen in the latest nightly version?

I believe this was fixed in #1230.

**Comment by MichaelPrust** [comment]
Still happening sporadically (very rare). 

Solved adding `interactivityResult.Result.Handled = true;` after calling `WaitForEventArgsAsync`.

![image](https://user-images.githubusercontent.com/13747320/164249187-14df5a1b-76b3-4691-9ca9-2124b795f872.png)

**Comment by MichaelPrust** [comment]
> > Still happening sporadically (very rare).
> > Solved adding `interactivityResult.Result.Handled = true;` after calling `WaitForEventArgsAsync`.
> 
> Can you give which version of D#+ you are using?

4.2.0-nightly-01107

**Comment by ExaInsanity** [comment]
That's a bit outdated (we're at 4.3.0 nightlies now) but I don't think there has been any change to it. I'll look into it at *some* point
