### ISSUE TITLE
Commands not being registered

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#1986]
### Summary

Running https://github.com/DSharpPlus/DSharpPlus/pull/1908, mixed with some other updates: https://github.com/VereTech-Gaming/DSharpPlus/actions/runs/9507103601)
For some reason commands never get registered. 
```
2024-06-14 00:32:17.548 +00:00 [ERR] Event handler exception for event INTERACTION_CREATED thrown from System.Threading.Tasks.Task ExecuteInteractionAsync(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.InteractionCreateEventArgs) (defined in DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor)
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.TryFindCommand(DiscordInteraction interaction, Command& command, IEnumerable`1& options)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ExecuteInteractionAsync(DiscordClient client, InteractionCreateEventArgs eventArgs)
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
```
With this, the slashy never responds and user is display with "application command failed within 3 seconds".
This was thought to have been fixed by https://github.com/DSharpPlus/DSharpPlus/pull/1972

-------------------------------------------------------------------------------------------------

Running a backport based off https://github.com/DSharpPlus/DSharpPlus/pull/1908 with https://github.com/DSharpPlus/DSharpPlus/pull/1972  (https://github.com/VereTech-Gaming/DSharpPlus/actions/runs/9750534303)
Again, commands do not register, 
```
2024-07-07 05:47:58.487 +00:00 [ERR] Request to {ULID}: {"message": "Invalid Form Body", "code": 50025, "errors": {"type": {"_errors: [{"code": "BASE_TYPE_CHOICES", "message": "Value must be one of {8}."}]}}}
```
This time however, the CommandErrored handler is invoked, and the discord user receives a reply, albeit only an error.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Ubuntu

### Reproduction Steps

It was originally thought that the cause was receiving an intereaction between GDC event invocation and commands registering. Now, idk.

**Comment by Plerx2493** [comment]
> This was thought to have been fixed by https://github.com/DSharpPlus/DSharpPlus/pull/1972
Does your custom branch contain this pr?

**Comment by ecrocombe** [comment]
![image](https://github.com/DSharpPlus/DSharpPlus/assets/42088209/71eb15ca-bff4-4409-92b0-600b8efed30f)

**Comment by ecrocombe** [comment]
Further looking into logs (running https://github.com/VereTech-Gaming/DSharpPlus/actions/runs/9507103601)

I see:
```
2024-06-14 00:06:11.327 +00:00 [ERR] Request to https://discord.com/api/v10/applications/1183388897384874094/commands triggered an exception
DSharpPlus.Exceptions.ServerErrorException: Internal Server Error: GatewayTimeout
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   ```
   ```
2024-06-14 00:06:11.328 +00:00 [ERR] Event handler exception for event GUILD_DOWNLOAD_COMPLETED thrown from System.Threading.Tasks.Task <ConfigureAsync>b__0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.GuildDownloadCompletedEventArgs) (defined in DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor+<>c__DisplayClass12_0)
DSharpPlus.Exceptions.ServerErrorException: Internal Server Error: GatewayTimeout
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGlobalApplicationCommandsAsync(UInt64 applicationId, IEnumerable`1 commands)
   at DSharpPlus.DiscordClient.BulkOverwriteGlobalApplicationCommandsAsync(IEnumerable`1 commands)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.RegisterSlashCommandsAsync(CommandsExtension extension)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.<>c__DisplayClass12_0.<<ConfigureAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
   ``` 
   
   Shortly followed by:
   ```
   2024-06-14 00:06:11.341 +00:00 [ERR] Socket handler suppressed an exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|500_1(IWebSocketClient sender, SocketMessageEventArgs e)
   ```
Are we closing the connection on large/slow uploads?

**Comment by Plerx2493** [comment]
> ![image](https://private-user-images.githubusercontent.com/42088209/346967967-71eb15ca-bff4-4409-92b0-600b8efed30f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA3ODgsIm5iZiI6MTcyMDUzMDQ4OCwicGF0aCI6Ii80MjA4ODIwOS8zNDY5Njc5NjctNzFlYjE1Y2EtYmZmNC00NDA5LTkyYjAtNjAwYjhlZmVkMzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEzMDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OTIxOTk2YzU3YWMyZDQ1NGEzYmJiNjkzNGM1Y2Q2M2FlMWE2MzUwMTM3MGQ2YzJhODQ0NGE1ZmQzYjFlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ur4Zh0YLrCtMeojmBhcBf7revF433Ah_tGIVhVlpL_I)

yeah i read that, but didnt saw the changes on your branch at first

**Comment by ecrocombe** [comment]
I ask because i have ~130 slash commands, all with names and descriptions
Lets say an average of 2 arguments each slashy.
Each argument has a name and a description. 
Thats 780 strings of names and descriptions.

I have localized ~30 languages.

Should my math be accurate, Thats 23,400 strings. I imagine my payload is large.

**Comment by Plerx2493** [comment]
> I ask because i have ~130 slash commands, all with names and descriptions Lets say an average of 2 arguments each slashy. Each argument has a name and a description. Thats 780 strings of names and descriptions.
> 
> I have localized ~30 languages.
> 
> Should my math be accurate, Thats 23,400 strings. I imagine my payload is large.

You could try to increase the timeout on the restclient.

```csharp
IServiceCollection.Configure<RestClientOptions>(x =>
{
    x.Timeout = TimeSpan.FromSeconds(30);
})
```

**Comment by akiraveliara** [comment]
(in your version; `DiscordConfiguration.HttpTimeout`)

**Comment by ecrocombe** [comment]
Thank you, I'll give that a try and let you know how I go.

**Comment by ecrocombe** [comment]
```
2024-07-09 20:24:12.580 +00:00 [ERR] Request to https://discord.com/api/v10/applications/1183388897384874094/commands triggered an exception
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DSharpPlus.Net.RestClient.<>c__DisplayClass11_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__8`1.<<ExecuteAsync>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, ResilienceContext context)
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   ```
   
   ```
   2024-07-09 20:24:12.582 +00:00 [ERR] Event handler exception for event GUILD_DOWNLOAD_COMPLETED thrown from System.Threading.Tasks.Task <ConfigureAsync>b__0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.GuildDownloadCompletedEventArgs) (defined in DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor+<>c__DisplayClass12_0)
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DSharpPlus.Net.RestClient.<>c__DisplayClass11_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__8`1.<<ExecuteAsync>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, ResilienceContext context)
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGlobalApplicationCommandsAsync(UInt64 applicationId, IEnumerable`1 commands)
   at DSharpPlus.DiscordClient.BulkOverwriteGlobalApplicationCommandsAsync(IEnumerable`1 commands)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.RegisterSlashCommandsAsync(CommandsExtension extension)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.<>c__DisplayClass12_0.<<ConfigureAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
   ```

**Comment by ecrocombe** [comment]
^^ Increased the timeout from the default (10 seconds), to 30 seconds.

**Comment by Plerx2493** [comment]
Tbh i have no idea what time would be expected for discord to take registering those

**Comment by ecrocombe** [comment]
Increased time out to 180 seconds last night in a desperate attempt to get the thing to start. It worked first go.

 To scared to restart again to see if it's a fluke.

**Comment by Plerx2493** [comment]
I will close this as complete. Feel free to reopen if the issue isnt permanently solved by the longer timeout.

**Comment by ecrocombe** [comment]
Timeout is still occurring on 180 seconds. Yet can sometimes work at 10 seconds.
This leads me to believe some sort of retry logic would be needed.

Is this something i can do my end?

**Comment by ecrocombe** [comment]
![image](https://github.com/user-attachments/assets/eb4dbe52-9848-4e84-a1ee-7522db112e44)
This is the payload to applications/:application_id/guilds/:guild_id/commands, as retrieved from the trace logs

1,412,140 characters

**Comment by Plerx2493** [comment]
maybe we should introduce for endpoints like this an option in our RestClient to make a request without timeout

**Comment by ecrocombe** [comment]
https://github.com/discord/discord-api-docs/issues/7021

**Comment by ecrocombe** [comment]
I did have some network issues previously, which our Hoster has now resolved. Issue still persists.

Updated to 5.0.0-nightly-02330.
```
2024-07-23 18:50:02.402 +00:00 [ERR] EventHandlerError::"DSharpPlus.EventArgs.SessionCreatedEventArgs" failed with "Internal Server Error: GatewayTimeout"
DSharpPlus.Exceptions.ServerErrorException: Internal Server Error: GatewayTimeout
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGlobalApplicationCommandsAsync(UInt64 applicationId, IEnumerable`1 commands)
   at DSharpPlus.DiscordClient.BulkOverwriteGlobalApplicationCommandsAsync(IEnumerable`1 commands)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.RegisterSlashCommandsAsync(CommandsExtension extension)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.<>c__DisplayClass15_0.<<ConfigureAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass8_0.<<InvokeAsync>b__0>d.MoveNext()
```

**Comment by Plerx2493** [comment]
Im not sure how to tackle this. Maybe we should add the cloudflare trace id (i think they call it ray) in our exceptions so we can use those to provide more information in the discord issue

**Comment by ecrocombe** [comment]
> Im not sure how to tackle this. Maybe we should add the cloudflare trace id (i think they call it ray) in our exceptions so we can use those to provide more information in the discord issue

To add to the confusion of this, I have not seen this fail in my dev bot (DEBUG build), 1 shard, 1 guild.

But as soon as i try on my main bot, it becomes an issue.

**Comment by ecrocombe** [comment]
Dev bot = 
- Same machine.
- Same IP
- Same Source Code (Debug Build)

**Comment by ecrocombe** [comment]
Today I:
- Turned off our main bot.
- Used the main bots token in our dev bot.
- Started up dev bot.
- Observed the dev bot now had the same issue.

**Comment by Plerx2493** [comment]
> Today I:
> - Turned off our main bot.
> - Used the main bots token in our dev bot.
> - Started up dev bot.
> - Observed the dev bot now had the same issue.

At this point I would reopen the discord issue and provide this information and also your main bots application id
